quaverGen/MvcApplication1/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcApplication1.Models
{
    public class Usuario
    {
        [ScaffoldColumn(false)]
        public int id { get; set; }

        [ScaffoldColumn(false)]
        public int IdCategoria { get; set; }

        /*    [ScaffoldColumn(false)]
        public IList<Comentario> { get; set; }*/
        //Tambien tengo que crear el model de comentario y el assembler

        /*    [ScaffoldColumn(false)]
      public IList<Entradas> { get; set; }*/

        //Model y Assembler van muy relacionados por que en el assembler asigno bien las variables que creo en el model
        //y todo esto es para los detalles del evento
        [Display(Prompt = "Nombre Usuario", Description = "Nombre del usuario", Name = "Nombre Usuario ")]
        [Required(ErrorMessage = "Debe indicar un nombre para el usuario")]
        [StringLength(maximumLength: 50, ErrorMessage = "El nombre no puede tener más de 50 caracteres")]
        public string Nombre_usu { get; set; }

        [Display(Prompt = "Nombre", Description = "Nombre del usuario", Name = "Nombre ")]
        [Required(ErrorMessage = "Debe indicar un nombre para el usuario")]
        [StringLength(maximumLength: 50, ErrorMessage = "El nombre no puede tener más de 50 caracteres")]
        public string Nombre { get; set; }

        [Display(Prompt = "Apellidos", Description = "Apellidos del usuario", Name = "Apellidos")]
        [Required(ErrorMessage = "Debe indicar un apellido para el usuario")]
        [StringLength(maximumLength: 50, ErrorMessage = "El apellido no puede tener más de 50 caracteres")]
        public string Apellidos { get; set; }

        [Display(Prompt = "Email", Description = "Dirección del usuario", Name = "Direccion")]
        [Required(ErrorMessage = "Debe indicar una dirrección para el usuario")]
        [StringLength(maximumLength: 50, ErrorMessage = "La dirección no puede tener más de 50 caracteres")]
        public string Correo { get; set; }

        [Display(Prompt = "Contraseña", Description = "Contraseña del usuario", Name = "Contraseña")]
        [Required(ErrorMessage = "Debe indicar una contraseña para el usuario")]
        [StringLength(maximumLength: 50, ErrorMessage = "La contraseña no puede tener más de 50 caracteres")]
        public string password { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha Nacimiento")]
        public Nullable<DateTime> Fecha { get; set; }

        [Display(Prompt = "Tipo", Description= "Tipo", Name= "Tipo")]
        [Required(ErrorMessage="Debe indicar un tipo de usuario")]
        public QuaverGenNHibernate.Enumerated.P3.TipoEnum TipoUsuario { get; set; }
        //Faltan Hora, Tipo, Incidencias, Entradas...
    }
 }

quaverGen/MvcApplication1/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using MvcApplication1.Filters;
using MvcApplication1.Models;
using QuaverGenNHibernate.CEN.P3;
using QuaverGenNHibernate.EN.P3;
using QuaverGenNHibernate.CAD.P3;
using System.IO;


namespace MvcApplication1.Controllers
{
    public class UsuarioController : BasicController
    {
        //
        // GET: /Usuario/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Usuario/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Usuario/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Usuario/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Usuario/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Usuario/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Usuario/Delete/5

        public ActionResult Delete(string id)
        {
            SessionInitialize();
            UsuarioCAD usuCAD = new UsuarioCAD(session);

            UsuarioEN usuEN = usuCAD.ReadOID(id);

            new UsuarioCEN().Borrar_cuenta(usuEN.Nombre_usuario);
            SessionClose();
            WebSecurity.Logout();
            return RedirectToAction("../Account/Login");

        }

        //
        // POST: /Usuario/Delete/5

        /*[HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }*/

        public ActionResult Perfil(string name)
        {
            //Usuario usu = null;
            SessionInitialize();
            UsuarioEN usuEN = new UsuarioCAD(session).ReadOIDDefault(name);
            //usu = new AssemblerUsuario().ConvertENToModelUI(usuEN);
            SessionClose();
            return View(usuEN);
        }

        public ActionResult Amigos(string name)
        {

            IEnumerable<UsuarioEN> amigos = null;
            IList<UsuarioEN> todos = new List<UsuarioEN>();
            IList<UsuarioEN> lista = new List<UsuarioEN>();
            bool encontrado = false;
            UsuarioEN usuCEN = new UsuarioEN();

            SessionInitialize();
            todos = new UsuarioCAD(session).ReadAllDefault(0,-1);
            if (todos != null)
            {
                foreach (var item in todos)
                {
                    if (item.Nombre_usuario.Equals(usuCEN.Amigo))
                    {
                        lista.Add(item);
                        encontrado = true;
                    }
                }
                if (encontrado)
                    amigos = lista.ToList();
                // todos = usuCEN.ReadAllDefault(0, -1);
            }
            SessionClose();
            return View(amigos);
        }

        public ActionResult Anyadir_amigo(string id)
        {
            SessionInitialize();

            IEnumerable<UsuarioEN> amigos = null;

            amigos = new UsuarioCAD(session).ReadAllDefault(0, 10).ToList();

            SessionClose();

            return View(amigos);
        }


        public ActionResult Anyadir_amigo_al_usuario(string name)
        {
            SessionInitialize();

            IEnumerable<UsuarioEN> users = null;
            IList<String> amigos = new List<String>();

            users = new UsuarioCAD(session).ReadAllDefault(0, 10).ToList();


            foreach (var item in users)
            {

                if (item.Nombre.Equals(name))
                {

                    amigos.Add(item.Nombre);
                }

            }


            UsuarioCAD usuCAD = new UsuarioCAD(session);

            usuCAD.Agregar_amigo(name, amigos);


            SessionClose();

            return RedirectToAction("Amigos");
        }
    }
}

quaverGen/MvcApplication1/Views/Usuario/Amigos.cshtml
@model IEnumerable<QuaverGenNHibernate.EN.P3.UsuarioEN>

@{
    ViewBag.Title = "Amigos";
}

<h2>Amigos</h2>

<p>
    <span class="apuntarse">@Html.ActionLink("Anyadir Amigo", "Anyadir_amigo", "Usuario", routeValues: new { User.Identity.Name }, htmlAttributes: null)</span>
</p>
@if (Model != null)
{
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellidos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_usuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>


        }
    </table>
}
else
{
    <p><strong>TODAVÍA NO TIENES AMIGOS, AÑADE ALGUNOS!!</strong></p>
}

quaverGen/MvcApplication1/Views/Usuario/Anyadir_amigo.cshtml
@model IEnumerable<QuaverGenNHibernate.EN.P3.UsuarioEN>
@{
    ViewBag.Title = "Anyadir amigo";

}

<h2>Añadir amigo</h2>


@if (Model != null)
{
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellidos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_usuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.ActionLink("Añadir", "Anyadir_amigo_al_usuario", new { name = item.Nombre_usuario })
                </td>
            </tr>


        }


    </table>

}

quaverGen/MvcApplication1/Views/Usuario/Borrar.cshtml
@model QuaverGenNHibernate.EN.P3.UsuarioEN

@{
    ViewBag.Title = "Borrar";
}

<h2>Borrar</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>UsuarioEN</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Apellidos)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Apellidos)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nombre_usuario)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre_usuario)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Contrasenya)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Contrasenya)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha_nac)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha_nac)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

quaverGen/MvcApplication1/Views/Usuario/Perfil.cshtml
@model QuaverGenNHibernate.EN.P3.UsuarioEN

@{
    ViewBag.Title = "Perfil";
}

<h2>Perfil</h2>

<div class="principal">
    <div class="eventos1">


        <!--Cambiar esto por la ruta de la imagen-->
        <div class="text-evento">
            <h1>@Html.DisplayFor(modelItem => Model.Nombre) @Html.DisplayFor(model => model.Apellidos)</h1>
            <br />
            <p><strong>Correo: </strong>@Html.DisplayFor(modelItem => Model.Email)</p>
            <p><strong>Fecha:  </strong>@Html.DisplayFor(modelItem => Model.Fecha_nac)</p>
            <p><strong>Tipo:  </strong>@Html.DisplayFor(modelItem => Model.Tipo_usuario)</p>



            @if (User.Identity.Name == Model.Nombre_usuario)
            {
                <span class="info">@Html.ActionLink("Editar", "Edit", new { /* id=Model.PrimaryKey */ })</span>
                <span class="info">@Html.ActionLink("Borrar", "Delete", new { id = Model.Nombre_usuario }, new { onclick = "return confirm('Seguro que quieres darte de baja " + Model.Nombre_usuario + "');" })</span>
                <span class="apuntarse">@Html.ActionLink("Mis Amigos", "Amigos", "Usuario", routeValues: new { User.Identity.Name }, htmlAttributes: null)</span>
            }
        </div>

    </div>