quaverGen/MvcApplication1/Models/Musica.cs
using QuaverGenNHibernate.EN.P3;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcApplication1.Models
{
    public class Musica
    {

        [ScaffoldColumn(false)]
        public int id { get; set; }

        [Display(Prompt = "Titulo canción", Description = "Titulo canción", Name = "Titulo canción")]
        [Required(ErrorMessage = "Debe indicar un nombre para la cancion")]
        [StringLength(maximumLength: 50, ErrorMessage = "La cancion no puede tener más de 50 caracteres")]
        public string titulo { get; set; }

        [Display(Prompt = "Género", Description = "Género canción", Name = "Género ")]
        [Required(ErrorMessage = "Debe un género")]
        [StringLength(maximumLength: 20, ErrorMessage = "El género no puede tener más de 20 caracteres")]
        public string genero { get; set; }

        [Display(Prompt = "Duración", Description = "Duración de la cancion", Name = "Duración")]
        [Required(ErrorMessage = "Debe indicar una duracion para la cancion")]
        public string duracion { get; set; }

        [Display(Prompt = "Usuario", Description = "nombre usuario", Name = "Usuario")]
        [Required(ErrorMessage = "Debe indicar un nombre para el usuario")]
        [StringLength(maximumLength: 50, ErrorMessage = "El nombre no puede tener más de 50 caracteres")]
        public string usuario { get; set; }

        [Display(Prompt = "Album", Description = "Album de la cancion", Name = "Album")]
        [Required(ErrorMessage = "Debe indicar un álbum para la canción")]
        [StringLength(maximumLength: 50, ErrorMessage = "El álbum no puede tener más de 50 caracteres")]
        public string album { get; set; }

        [Display(Prompt = "Artista", Description = "Artista", Name = "Artista")]
        [Required(ErrorMessage = "Debe indicar un artista")]
        public IList<ArtistasEN>artista { get; set; }

        [Display(Prompt = "Valoración", Description = "Valoración de la canción", Name = "Valoración")]
        [Required(ErrorMessage = "Debe indicar una valoración")]
        public ValoracionesEN valoracion { get; set; }

        [Display(Prompt = "Minuto ", Description = "Minuto de la cancion", Name = "Minuto")]
        [Required(ErrorMessage = "Debe indicar un minuto")]
        public Nullable<DateTime> minuto { get; set; }

        [Display(Prompt = "Letra", Description = "Letra", Name = "Letra")]
        [Required(ErrorMessage = "Debe indicar una letra")]
        public string letra { get; set; }
    }
}

quaverGen/MvcApplication1/Controllers/CancionController.cs
using MvcApplication1.Models;
using QuaverGenNHibernate.CAD.P3;
using QuaverGenNHibernate.CEN.P3;
using QuaverGenNHibernate.EN.P3;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class CancionController : BasicController
    {
        //
        // GET: /Cancion/

        [HttpPost]
        public ActionResult Anyadir_cancion(CancionEN cancion)
        {
            try
            {
                // TODO: Add insert logic here

                CancionCEN cen = new CancionCEN();
                //necesito un usuario cen

                string auxiliar = cen.New_(cancion.Nombre, cancion.Genero, cancion.Duracion, cancion.R_album, cancion.Artistas, cancion.Min_cancion, cancion.Letra);

                return RedirectToAction("Musica", "Home");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Index()
        {
            CancionCEN caCEN = new CancionCEN();
            //var result = evCEN.get_IEventoCAD();
            IEnumerable<CancionEN> list = caCEN.ReadAll(0, -1).ToList();
            return View(list);
        }

        //
        // GET: /Cancion/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Cancion/Create

        public ActionResult Create()
        {
            Musica cancion = new Musica();
            return View(cancion);
        }

        //
        // POST: /Cancion/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Cancion/Edit/5

        public ActionResult Edit(string id)
        {
            Musica art = null;
            SessionInitialize();
            CancionEN artEN = new CancionCAD(session).ReadOIDDefault(id);
       
            art = new AssemblerMusica().ConvertENToModelUI(artEN);
            SessionClose();
            return View(art);
        }


        //
        // POST: /Cancion/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Cancion/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Cancion/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public NHibernate.ISession session { get; set; }

        public ActionResult Buscar(string palabra)
        {
            IEnumerable<CancionEN> list = null;
            IList<CancionEN> lista = new List<CancionEN>();
            CancionCEN caCEN = new CancionCEN();
            bool ok = false;
            SessionInitialize();
            if (palabra != null)
            {
                list = caCEN.ReadNombre(palabra).ToList();
                if (list == null)
                {
                    ok = true;
                    lista = caCEN.ReadArtista(palabra).ToList();
                    list = lista.ToList();
                }
            }
            SessionClose();

            if (ok == true && lista.Count < 1)
            {
                return RedirectToAction("Buscar", "Musica", routeValues: new { palabra = palabra });
            }
            else
            {
                return View(list);
            }
        }

        public ActionResult Busqueda_avanzada(string nombre, string artista)
        {
            IEnumerable<CancionEN> list = null;
            List<CancionEN> lista = new List<CancionEN>();
            CancionCEN caCEN = new CancionCEN();
            bool ok = false;
            SessionInitialize();
            if (nombre != "")
            {
                list = caCEN.ReadNombre(nombre).ToList();
                if (artista != "")
                {
                    foreach (CancionEN item in list)
                    {
                        if (item.Artistas.ElementAt(0).Nombre == artista)
                        {
                            lista.Add(item);
                            ok = true;
                        }
                    }
                    if (ok)
                        list = lista.ToList();
                }
            }
            if (nombre == "" && artista != "")
            {
                list = caCEN.ReadArtista(artista).ToList();
            }


            SessionClose();
            return View(list);
        }
    }
}

quaverGen/MvcApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using MvcApplication1.Filters;
using MvcApplication1.Models;
using QuaverGenNHibernate.CEN.P3;
using QuaverGenNHibernate.EN.P3;
using QuaverGenNHibernate.CAD.P3;
using System.IO;


namespace MvcApplication1.Controllers
{
    public class HomeController : BasicController
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Musica()
        {
            CancionCEN canCEN = new CancionCEN();
            IEnumerable<CancionEN> canciones = canCEN.ReadAll(0, -1).ToList();

            return View(canciones);
        }
    }
}

quaverGen/MvcApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

quaverGen/MvcApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

quaverGen/MvcApplication1/Views/Home/Index.cshtml
<body>
   
    <!--Menú
    <nav class="navbar navbar-default panel">
        <div class="menu">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
         
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li role="presentation"><a class="putavida" href="index.html#gestion">Explorar</a></li>
                    <li role="presentation"><a href="index.html#sesiones">Radio</a></li>
                    <li role="presentation"><a href="index.html#imagenes">Historial</a></li>
                    <li role="presentation"><a href="index.html#audio">Mis datos </a></li>
                </ul>
            </div>
        </div>
    </nav>-->

  
    <!--Botón desplegable
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Dropdown
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>
    -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="Scripts/bootstrap.min.js"></script>

    <div class="contenido">

    <h2>Te recomendamos</h2>
        <div class="recomendaciones">
            <ul class="cancioncejas">
               
               <li><img src="http://images.coveralia.com/audio/i/Izal-Copacabana-Frontal.jpg" width="250px" height="250px"></li>
               
                <li>Copacabana</li>
                <li>Izal</li>
                <li>Copacabana</li>
                <li class="mambo"><a href="javascript:player.play();" class="btn btn-default"><i class="glyphicon glyphicon-play"></i></a></li>
                
                
                   
            </ul>

            <ul class="cancioncejas">

                <li><img src="http://images.coveralia.com/audio/s/Sia-This_Is_Acting-Frontal.jpg" width="250px" height="250px"></li>

                <li>The Greatest</li>
                <li>Sia</li>
                <li>The Greatest</li>
                



            </ul>

        </div>
    </div>

  

    <div class="reproductor">
           

            <script src="Scripts/reproductor.js"></script>
            <script src="Scripts/rep.js"></script>

                 <audio id="player" class="color" controls></audio>
                    <div class="col-md-6 col-md-offset-3">



                        <div class="tcenter">
                            <a href="javascript:backSong();" class="btn btn-default"><i class="glyphicon glyphicon-backward"></i></a>
                            <a href="javascript:player.load();" class="btn btn-default"><i class="glyphicon glyphicon-stop"></i></a>
                           <a href="javascript:player.play();" class="btn btn-default"><i class="glyphicon glyphicon-play"></i></a>
                            <a href="javascript:player.pause();" class="btn btn-default"><i class="glyphicon glyphicon-pause"></i></a>
                            <a href="javascript:nextSong();" class="btn btn-default"><i class="glyphicon glyphicon-forward"></i></a>
                        </div> <!-- /.tcenter -->

                  

                    </div> <!-- /.col-mid -->

    

        </div>


</body>




  </body>
</html>

quaverGen/MvcApplication1/Views/Home/Musica.cshtml
@model IEnumerable<QuaverGenNHibernate.EN.P3.CancionEN>

@{
    ViewBag.Title = "Tu música";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tu Música</h2>

<span class="apuntarse">@Html.ActionLink("Añadir canción", "Anyadir_cancion", "Cancion")</span>


@if (Model != null) {
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duracion)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duracion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

    </table>
}else{
    <p><strong>TODAVÍA NO TIENES CANCIONES, AÑADE ALGUNA!!</strong></p>
}